using System.Text;

namespace Protogen;

/// <summary>
/// 从协议模型生成 C# 代码：
/// - MessageIds.g.cs   : 消息 ID 常量
/// - Messages.g.cs     : 消息/结构体类（MemoryPack 二进制序列化）
/// - RouterTable.g.cs  : MsgId -> 目标服务器 配置化路由表
/// </summary>
public static class CodeGenerator
{
    // 类型映射：def type -> C# 类型
    private static readonly Dictionary<string, string> TypeMap = new()
    {
        ["bool"] = "bool",
        ["int8"] = "sbyte",
        ["uint8"] = "byte",
        ["int16"] = "short",
        ["uint16"] = "ushort",
        ["int32"] = "int",
        ["uint32"] = "uint",
        ["int64"] = "long",
        ["uint64"] = "ulong",
        ["float"] = "float",
        ["double"] = "double",
        ["string"] = "string",
        ["bytes"] = "byte[]",
    };

    /// <summary>把 def 类型表达式转换为 C# 类型（支持 list:T / map:K,V / 结构体引用）</summary>
    public static string ToCSharpType(string type)
    {
        if (type.StartsWith("list:", StringComparison.Ordinal))
        {
            return $"List<{ToCSharpType(type["list:".Length..])}>";
        }
        if (type.StartsWith("map:", StringComparison.Ordinal))
        {
            var parts = type["map:".Length..].Split(',');
            return $"Dictionary<{ToCSharpType(parts[0])}, {ToCSharpType(parts[1])}>";
        }
        return TypeMap.TryGetValue(type, out var cs) ? cs : type; // 结构体引用直接用类型名
    }

    /// <summary>属性默认值表达式</summary>
    public static string DefaultValue(string type)
    {
        string cs = ToCSharpType(type);
        return cs switch
        {
            "string" => "string.Empty",
            "byte[]" => "Array.Empty<byte>()",
            _ when cs.StartsWith("List<") => "new()",
            _ when cs.StartsWith("Dictionary<") => "new()",
            _ when cs is "bool" or "sbyte" or "byte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong" or "float" or "double" => "default",
            _ => "new()" // 结构体/自定义类型：非空实例
        };
    }

    public static string GenerateMessageIds(List<ProtocolModel> protocols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 由 Protogen 生成，请勿手动修改。");
        sb.AppendLine("namespace Framework.Protocol.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>全协议消息 ID 常量（唯一事实来源：Protocol/defs/*.def）</summary>");
        sb.AppendLine("public static class MessageIds");
        sb.AppendLine("{");
        foreach (var proto in protocols)
        {
            foreach (var msg in proto.Messages)
            {
                string fieldName = Sanitize(msg.Name);
                sb.AppendLine($"    /// <summary>{msg.Id} {msg.Name} -> {msg.Target}{(msg.Internal ? " [internal]" : "")}</summary>");
                sb.AppendLine($"    public const int {fieldName} = {msg.Id};");
            }
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateMessages(List<ProtocolModel> protocols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 由 Protogen 生成，请勿手动修改。");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using Framework.Protocol;");
        sb.AppendLine();
        sb.AppendLine("namespace Framework.Protocol.Generated;");
        sb.AppendLine();

        foreach (var proto in protocols)
        {
            foreach (var s in proto.Structs)
            {
                AppendStruct(sb, s);
            }
            foreach (var msg in proto.Messages)
            {
                AppendMessage(sb, msg);
            }
        }

        return sb.ToString();
    }

    private static void AppendStruct(StringBuilder sb, StructModel s)
    {
        string name = Sanitize(s.Name);
        sb.AppendLine($"[MemoryPackable]");
        sb.AppendLine($"public partial class {name}");
        sb.AppendLine("{");
        foreach (var f in s.Fields)
        {
            string cs = ToCSharpType(f.Type);
            sb.AppendLine($"    public {cs} {Sanitize(f.Name)} {{ get; set; }} = {DefaultValue(f.Type)};");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendMessage(StringBuilder sb, MessageModel msg)
    {
        string name = Sanitize(msg.Name);
        sb.AppendLine($"[MemoryPackable]");
        sb.AppendLine($"public partial class {name} : IGameMessage");
        sb.AppendLine("{");
        sb.AppendLine($"    public const int MsgId = {msg.Id};");
        sb.AppendLine($"    public const string TargetServer = \"{msg.Target}\";");
        sb.AppendLine($"    int IGameMessage.MessageId => MsgId;");
        sb.AppendLine($"    /// <summary>序列化为 MemoryPack 二进制负载（不含帧头）。</summary>");
        sb.AppendLine($"    public byte[] Serialize() => MemoryPackSerializer.Serialize(this);");
        sb.AppendLine($"    /// <summary>从二进制负载反序列化。</summary>");
        sb.AppendLine($"    public static {name}? Deserialize(ReadOnlySpan<byte> payload) => MemoryPackSerializer.Deserialize<{name}>(payload);");
        foreach (var f in msg.Fields)
        {
            string cs = ToCSharpType(f.Type);
            sb.AppendLine($"    public {cs} {Sanitize(f.Name)} {{ get; set; }} = {DefaultValue(f.Type)};");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>生成路由表：MsgId -> (目标服务器, 类型)。Gateway 据此配置化转发。</summary>
    public static string GenerateRouterTable(List<ProtocolModel> protocols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 由 Protogen 生成，请勿手动修改。");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Framework.Protocol.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>消息路由信息</summary>");
        sb.AppendLine("public readonly record struct MessageRouteInfo(int MsgId, string Name, string TargetServer, Type? MessageType, bool IsInternal);");
        sb.AppendLine();
        sb.AppendLine("/// <summary>配置化路由表：由 Protocol/defs/*.def 生成，Gateway 与各业务服共用。</summary>");
        sb.AppendLine("public static class RouterTable");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>MsgId -> 路由信息</summary>");
        sb.AppendLine("    public static readonly IReadOnlyDictionary<int, MessageRouteInfo> Routes = new Dictionary<int, MessageRouteInfo>");
        sb.AppendLine("    {");

        foreach (var proto in protocols)
        {
            foreach (var msg in proto.Messages)
            {
                string name = Sanitize(msg.Name);
                sb.AppendLine($"        [{msg.Id}] = new MessageRouteInfo({msg.Id}, \"{msg.Name}\", \"{msg.Target}\", typeof({name}), {(msg.Internal ? "true" : "false")}),");
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>根据 MsgId 查询目标服务器；未定义时返回 null。</summary>");
        sb.AppendLine("    public static string? GetTargetServer(int msgId)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Routes.TryGetValue(msgId, out var info) ? info.TargetServer : null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>根据 MsgId 查询消息类型；未定义时返回 null。</summary>");
        sb.AppendLine("    public static Type? GetMessageType(int msgId)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Routes.TryGetValue(msgId, out var info) ? info.MessageType : null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Sanitize(string name)
    {
        var sb = new StringBuilder(name.Length + 2);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch)) sb.Append(ch);
            else sb.Append('_');
        }
        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }
}
