using System.Text;

namespace ClientGen;

/// <summary>
/// Unreal Engine / C++ 客户端生成器（零引擎依赖、header-only、标准 socket）：
///   MemoryPack.h  —— 与服务器 MemoryPack 二进制格式逐字节兼容的编解码器
///   Messages.h    —— 消息结构体 + Serialize/Deserialize + <Name>MsgId 常量
///   NetClient.*   —— 标准 TCP 客户端（Windows/Winsock 与 Linux/POSIX 双平台）
/// 编解码逻辑与 Unity C# 侧（UnityGenerator）逐行对应，同一算法两份实现。
/// </summary>
public static class UeGenerator
{
    public static string GenerateMemoryPackH() => MemoryPackH;

    public static string GenerateMessagesH(List<ProtocolModel> protocols) => BuildMessagesH(protocols);

    public static string GenerateNetClientH() => NetClientH;

    public static string GenerateNetClientCpp() => NetClientCpp;

    public static string GenerateDemoCpp() => DemoCpp;

    public static string GenerateReadme() => Readme;

    // ---------- Messages.h ----------

    private static string BuildMessagesH(List<ProtocolModel> protocols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 由 ClientGen 生成，请勿手动修改。");
        sb.AppendLine("#pragma once");
        sb.AppendLine("// 客户端消息定义（与服务器 Framework.Protocol.Generated 二进制兼容，MemoryPack 格式）。");
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine("#include <map>");
        sb.AppendLine("#include <string>");
        sb.AppendLine("#include <vector>");
        sb.AppendLine("#include \"MemoryPack.h\"");
        sb.AppendLine();
        sb.AppendLine("namespace ClientProtocol");
        sb.AppendLine("{");

        // 结构体按依赖拓扑排序（被引用的先输出）
        foreach (var s in TopoSortStructs(protocols))
        {
            AppendStruct(sb, s, protocols);
        }

        foreach (var proto in protocols)
        {
            foreach (var msg in proto.Messages)
            {
                AppendMessage(sb, msg, protocols);
            }
        }

        // 消息 ID 常量（<Name>MsgId 避免与结构体同名冲突）
        sb.AppendLine("    /// <summary>消息 ID 常量。</summary>");
        foreach (var proto in protocols)
        {
            foreach (var msg in proto.Messages)
            {
                sb.AppendLine($"    inline constexpr int32_t {Sanitize(msg.Name)}MsgId = {msg.Id};");
            }
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static IEnumerable<string> StructRefs(string type, List<ProtocolModel> protocols)
    {
        var kind = TypeHelpers.KindOf(type, protocols);
        if (kind == FieldKind.Struct)
        {
            yield return type;
        }
        else if (kind == FieldKind.List)
        {
            foreach (var r in StructRefs(TypeHelpers.InnerOf(type), protocols)) yield return r;
        }
        else if (kind == FieldKind.Map)
        {
            var (k, v) = TypeHelpers.MapPartsOf(type);
            foreach (var r in StructRefs(k, protocols)) yield return r;
            foreach (var r in StructRefs(v, protocols)) yield return r;
        }
    }

    private static List<StructModel> TopoSortStructs(List<ProtocolModel> protocols)
    {
        var all = protocols.SelectMany(p => p.Structs).ToList();
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<StructModel>();
        int guard = 0;
        while (result.Count < all.Count && guard++ < all.Count + 1)
        {
            bool added = false;
            foreach (var s in all)
            {
                if (emitted.Contains(s.Name)) continue;
                bool ready = s.Fields.All(f => StructRefs(f.Type, protocols).All(emitted.Contains));
                if (ready)
                {
                    result.Add(s);
                    emitted.Add(s.Name);
                    added = true;
                }
            }
            if (!added) break; // 循环引用（.def 不应出现）
        }
        // 兜底：仍未输出的结构体追加到末尾（避免漏掉）
        foreach (var s in all)
        {
            if (!emitted.Contains(s.Name)) result.Add(s);
        }
        return result;
    }

    private static void AppendStruct(StringBuilder sb, StructModel s, List<ProtocolModel> protocols)
    {
        sb.AppendLine($"/// <summary>结构体 {s.Name}（{s.Fields.Count} 个成员）。</summary>");
        sb.AppendLine($"struct {s.Name}");
        sb.AppendLine("{");
        foreach (var f in s.Fields)
        {
            sb.AppendLine($"    {CppType(f.Type, protocols)} {f.Name}{CppDefault(f.Type, protocols)};");
        }
        sb.AppendLine();
        sb.AppendLine("    /// <summary>写入成员数据（不含对象头字节；直接结构体字段会写入自身对象头）。</summary>");
        sb.AppendLine("    void WriteBody(mp::Writer& w) const");
        sb.AppendLine("    {");
        foreach (var f in s.Fields)
        {
            sb.AppendLine($"        {CppWrite(f.Name, f.Type, protocols)}");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>读取成员数据（不含对象头）。</summary>");
        sb.AppendLine("    void ReadBody(mp::Reader& r)");
        sb.AppendLine("    {");
        foreach (var f in s.Fields)
        {
            sb.AppendLine($"        {CppRead(f.Name, f.Type, protocols)}");
        }
        sb.AppendLine("    }");
        sb.AppendLine("};");
        sb.AppendLine();
    }

    private static void AppendMessage(StringBuilder sb, MessageModel msg, List<ProtocolModel> protocols)
    {
        sb.AppendLine($"/// <summary>{msg.Id} {msg.Name} -> {msg.Target}（服务器目标 {msg.Target}）。</summary>");
        sb.AppendLine($"struct {msg.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"    static constexpr int32_t MsgId = {msg.Id};");
        sb.AppendLine($"    static constexpr const char* Target = \"{msg.Target}\";");
        foreach (var f in msg.Fields)
        {
            sb.AppendLine($"    {CppType(f.Type, protocols)} {f.Name}{CppDefault(f.Type, protocols)};");
        }
        sb.AppendLine();
        sb.AppendLine("    /// <summary>序列化为完整负载（对象头 + 成员数据），不含帧头。</summary>");
        sb.AppendLine("    std::vector<uint8_t> Serialize() const");
        sb.AppendLine("    {");
        sb.AppendLine("        mp::Writer w;");
        sb.AppendLine($"        w.WriteHeader({msg.Fields.Count});");
        sb.AppendLine("        WriteBody(w);");
        sb.AppendLine("        return w.Take();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    void WriteBody(mp::Writer& w) const");
        sb.AppendLine("    {");
        foreach (var f in msg.Fields)
        {
            sb.AppendLine($"        {CppWrite(f.Name, f.Type, protocols)}");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    void ReadBody(mp::Reader& r)");
        sb.AppendLine("    {");
        foreach (var f in msg.Fields)
        {
            sb.AppendLine($"        {CppRead(f.Name, f.Type, protocols)}");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>从负载反序列化（跳过对象头后读成员数据）。</summary>");
        sb.AppendLine($"    static {msg.Name} Deserialize(const uint8_t* data, size_t size)");
        sb.AppendLine("    {");
        sb.AppendLine("        mp::Reader r(data, size);");
        sb.AppendLine("        r.SkipHeader();");
        sb.AppendLine($"        {msg.Name} m;");
        sb.AppendLine("        m.ReadBody(r);");
        sb.AppendLine("        return m;");
        sb.AppendLine("    }");
        sb.AppendLine("};");
        sb.AppendLine();
    }

    // ---------- C++ type / expr mapping ----------

    private static string CppType(string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => "bool",
            FieldKind.Int32 => "int32_t",
            FieldKind.Int64 => "int64_t",
            FieldKind.Float => "float",
            FieldKind.String => "std::string",
            FieldKind.Bytes => "std::vector<uint8_t>",
            FieldKind.List => $"std::vector<{CppType(TypeHelpers.InnerOf(type), protocols)}>",
            FieldKind.Map => CppMapType(type, protocols),
            FieldKind.Struct => type,
            _ => "std::string",
        };
    }

    private static string CppMapType(string type, List<ProtocolModel> protocols)
    {
        var (k, v) = TypeHelpers.MapPartsOf(type);
        return $"std::map<{CppType(k, protocols)}, {CppType(v, protocols)}>";
    }

    private static int MemberCount(string structName, List<ProtocolModel> protocols)
    {
        var st = ClientModel.FindStruct(protocols, structName);
        return st?.Fields.Count ?? 0;
    }

    private static string CppDefault(string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => " = false",
            FieldKind.Int32 => " = 0",
            FieldKind.Int64 => " = 0",
            FieldKind.Float => " = 0.0f",
            _ => "",
        };
    }

    private static string CppWrite(string field, string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => $"w.WriteBool({field});",
            FieldKind.Int32 => $"w.WriteI32({field});",
            FieldKind.Int64 => $"w.WriteI64({field});",
            FieldKind.Float => $"w.WriteFloat({field});",
            FieldKind.String => $"w.WriteString({field});",
            FieldKind.Bytes => $"w.WriteBytes({field});",
            FieldKind.List => CppWriteList(field, TypeHelpers.InnerOf(type), protocols),
            FieldKind.Map => CppWriteMap(field, type, protocols),
            FieldKind.Struct => $"w.WriteHeader({MemberCount(type, protocols)}); {field}.WriteBody(w);",
            _ => "",
        };
    }

    private static string CppWriteList(string field, string inner, List<ProtocolModel> protocols)
    {
        string elem = TypeHelpers.KindOf(inner, protocols) switch
        {
            FieldKind.Bool => "w.WriteBool(it);",
            FieldKind.Int32 => "w.WriteI32(it);",
            FieldKind.Int64 => "w.WriteI64(it);",
            FieldKind.Float => "w.WriteFloat(it);",
            FieldKind.String => "w.WriteString(it);",
            FieldKind.Bytes => "w.WriteBytes(it);",
            FieldKind.Struct => $"w.WriteHeader({MemberCount(inner, protocols)}); it.WriteBody(w);",
            _ => "",
        };
        return $"w.WriteCount((int32_t){field}.size()); for (const auto& it : {field}) {{ {elem} }}";
    }

    private static string CppWriteMap(string field, string type, List<ProtocolModel> protocols)
    {
        var (k, v) = TypeHelpers.MapPartsOf(type);
        string key = CppWriteMapItem("kv.first", k, protocols);
        string val = CppWriteMapItem("kv.second", v, protocols);
        return $"w.WriteCount((int32_t){field}.size()); for (const auto& kv : {field}) {{ {key} {val} }}";
    }

    private static string CppWriteMapItem(string expr, string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => $"w.WriteBool({expr});",
            FieldKind.Int32 => $"w.WriteI32({expr});",
            FieldKind.Int64 => $"w.WriteI64({expr});",
            FieldKind.Float => $"w.WriteFloat({expr});",
            FieldKind.String => $"w.WriteString({expr});",
            FieldKind.Bytes => $"w.WriteBytes({expr});",
            FieldKind.Struct => $"w.WriteHeader({MemberCount(type, protocols)}); {expr}.WriteBody(w);",
            _ => "",
        };
    }

    private static string CppRead(string field, string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => $"{field} = r.ReadBool();",
            FieldKind.Int32 => $"{field} = r.ReadI32();",
            FieldKind.Int64 => $"{field} = r.ReadI64();",
            FieldKind.Float => $"{field} = r.ReadFloat();",
            FieldKind.String => $"{field} = r.ReadString();",
            FieldKind.Bytes => $"{field} = r.ReadBytes();",
            FieldKind.List => CppReadList(field, TypeHelpers.InnerOf(type), protocols),
            FieldKind.Map => CppReadMap(field, type, protocols),
            FieldKind.Struct => $"r.SkipHeader(); {field}.ReadBody(r);",
            _ => "",
        };
    }

    private static string CppReadList(string field, string inner, List<ProtocolModel> protocols)
    {
        string elem = TypeHelpers.KindOf(inner, protocols) switch
        {
            FieldKind.Bool => "bool _e = r.ReadBool();",
            FieldKind.Int32 => "int32_t _e = r.ReadI32();",
            FieldKind.Int64 => "int64_t _e = r.ReadI64();",
            FieldKind.Float => "float _e = r.ReadFloat();",
            FieldKind.String => "std::string _e = r.ReadString();",
            FieldKind.Bytes => "std::vector<uint8_t> _e = r.ReadBytes();",
            FieldKind.Struct => $"{inner} _e; r.SkipHeader(); _e.ReadBody(r);",
            _ => "",
        };
        return $"int32_t _n = r.ReadCount(); {field}.clear(); {field}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; ++_i) {{ {elem} {field}.push_back(_e); }}";
    }

    private static string CppReadMap(string field, string type, List<ProtocolModel> protocols)
    {
        var (k, v) = TypeHelpers.MapPartsOf(type);
        string key = CppReadMapPart("_k", k, protocols);
        string val = CppReadMapPart("_v", v, protocols);
        return $"int32_t _n = r.ReadCount(); {field}.clear(); for (int32_t _i = 0; _i < _n; ++_i) {{ {key} {val} {field}[_k] = _v; }}";
    }

    private static string CppReadMapPart(string varName, string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => $"bool {varName} = r.ReadBool();",
            FieldKind.Int32 => $"int32_t {varName} = r.ReadI32();",
            FieldKind.Int64 => $"int64_t {varName} = r.ReadI64();",
            FieldKind.Float => $"float {varName} = r.ReadFloat();",
            FieldKind.String => $"std::string {varName} = r.ReadString();",
            FieldKind.Bytes => $"std::vector<uint8_t> {varName} = r.ReadBytes();",
            FieldKind.Struct => $"{type} {varName}; r.SkipHeader(); {varName}.ReadBody(r);",
            _ => $"int32_t {varName} = r.ReadI32();",
        };
    }

    private static string Sanitize(string name)
    {
        var sb = new StringBuilder(name.Length + 2);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch)) sb.Append(ch);
            else sb.Append('_');
        }
        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }

    // ---------- templates ----------

    private const string MemoryPackH = """
// <auto-generated> 由 ClientGen 生成，请勿手动修改。
#pragma once
// 与服务器 MemoryPack 二进制格式逐字节兼容的零依赖编解码器（纯 C++11，header-only）。
// 格式要点（经真实 MemoryPack 输出实证）：
//   - 每个类对象（根对象 / 直接结构体字段 / 集合元素 / map 值）：1 字节对象头 = 成员数
//   - 数值：定长小端（bool=1 / int32=4 / int64=8 / float=4 / double=8）
//   - 字符串：int32(~utf8len) + int32(utf16len) + UTF-8 字节；空串 = int32(0)
//   - byte[]：int32(len) + 字节
//   - List/Map：int32(count) + 元素（结构体元素带对象头）
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

namespace mp {

// 统计 UTF-8 字节串对应的 UTF-16 码元数（与 C# string.Length / .NET char 数一致）
inline int32_t Utf16Length(const std::string& utf8) {
    int32_t n = 0;
    size_t i = 0;
    const size_t len = utf8.size();
    while (i < len) {
        uint8_t c = (uint8_t)utf8[i];
        if (c < 0x80) { n += 1; i += 1; }
        else if ((c >> 5) == 0x06) { n += 1; i += 2; }       // 2 字节
        else if ((c >> 4) == 0x0E) { n += 1; i += 3; }       // 3 字节（BMP）
        else if ((c >> 3) == 0x1E) { n += 2; i += 4; }       // 4 字节（代理对 = 2 码元）
        else { i += 1; }
    }
    return n;
}

/// <summary>MemoryPack 兼容二进制写入器。</summary>
class Writer {
public:
    void WriteByte(uint8_t v) { buf_.push_back(v); }
    void WriteHeader(int memberCount) { buf_.push_back((uint8_t)memberCount); }
    void WriteBool(bool v) { buf_.push_back(v ? 1 : 0); }
    void WriteI32(int32_t v) {
        buf_.push_back((uint8_t)(v & 0xFF));
        buf_.push_back((uint8_t)((v >> 8) & 0xFF));
        buf_.push_back((uint8_t)((v >> 16) & 0xFF));
        buf_.push_back((uint8_t)((v >> 24) & 0xFF));
    }
    void WriteI64(int64_t v) {
        buf_.push_back((uint8_t)(v & 0xFF));
        buf_.push_back((uint8_t)((v >> 8) & 0xFF));
        buf_.push_back((uint8_t)((v >> 16) & 0xFF));
        buf_.push_back((uint8_t)((v >> 24) & 0xFF));
        buf_.push_back((uint8_t)((v >> 32) & 0xFF));
        buf_.push_back((uint8_t)((v >> 40) & 0xFF));
        buf_.push_back((uint8_t)((v >> 48) & 0xFF));
        buf_.push_back((uint8_t)((v >> 56) & 0xFF));
    }
    void WriteFloat(float f) { uint32_t u; std::memcpy(&u, &f, 4); WriteU32(u); }
    void WriteDouble(double d) { uint64_t u; std::memcpy(&u, &d, 8); WriteU64(u); }

    void WriteString(const std::string& s) {
        if (s.empty()) { WriteI32(0); return; }
        int32_t utf8Len = (int32_t)s.size();
        int32_t utf16Len = Utf16Length(s);
        WriteI32(~utf8Len);
        WriteI32(utf16Len);
        buf_.insert(buf_.end(), s.begin(), s.end());
    }

    void WriteBytes(const std::vector<uint8_t>& b) {
        WriteI32((int32_t)b.size());
        if (!b.empty()) buf_.insert(buf_.end(), b.begin(), b.end());
    }

    void WriteCount(int32_t n) { WriteI32(n); }

    std::vector<uint8_t> Take() { return std::move(buf_); }

private:
    void WriteU32(uint32_t v) {
        buf_.push_back((uint8_t)(v & 0xFF));
        buf_.push_back((uint8_t)((v >> 8) & 0xFF));
        buf_.push_back((uint8_t)((v >> 16) & 0xFF));
        buf_.push_back((uint8_t)((v >> 24) & 0xFF));
    }
    void WriteU64(uint64_t v) {
        buf_.push_back((uint8_t)(v & 0xFF));
        buf_.push_back((uint8_t)((v >> 8) & 0xFF));
        buf_.push_back((uint8_t)((v >> 16) & 0xFF));
        buf_.push_back((uint8_t)((v >> 24) & 0xFF));
        buf_.push_back((uint8_t)((v >> 32) & 0xFF));
        buf_.push_back((uint8_t)((v >> 40) & 0xFF));
        buf_.push_back((uint8_t)((v >> 48) & 0xFF));
        buf_.push_back((uint8_t)((v >> 56) & 0xFF));
    }
    std::vector<uint8_t> buf_;
};

/// <summary>MemoryPack 兼容二进制读取器（带越界保护）。</summary>
class Reader {
public:
    Reader(const uint8_t* data, size_t size) : data_(data), size_(size), pos_(0) {}

    void SkipHeader() { pos_ += 1; }
    bool Ok() const { return pos_ <= size_; }
    size_t Remaining() const { return size_ - pos_; }

    bool ReadBool() { return ReadByte() != 0; }

    int32_t ReadI32() {
        if (Remaining() < 4) return 0;
        uint32_t v = (uint32_t)data_[pos_] | ((uint32_t)data_[pos_ + 1] << 8)
                   | ((uint32_t)data_[pos_ + 2] << 16) | ((uint32_t)data_[pos_ + 3] << 24);
        pos_ += 4;
        return (int32_t)v;
    }

    int64_t ReadI64() {
        uint64_t lo = (uint32_t)ReadI32();
        uint64_t hi = (uint32_t)ReadI32();
        return (int64_t)(lo | (hi << 32));
    }

    float ReadFloat() {
        uint32_t u = (uint32_t)ReadI32();
        float f;
        std::memcpy(&f, &u, 4);
        return f;
    }

    double ReadDouble() {
        uint64_t lo = (uint32_t)ReadI32();
        uint64_t hi = (uint32_t)ReadI32();
        uint64_t u = lo | (hi << 32);
        double d;
        std::memcpy(&d, &u, 8);
        return d;
    }

    std::string ReadString() {
        int32_t v = ReadI32();
        if (v == 0) return std::string();
        int32_t utf8Len = ~v;
        ReadI32(); // UTF-16 长度（客户端只需 UTF-8 字节）
        if (Remaining() < (size_t)utf8Len) { pos_ = size_; return std::string(); }
        std::string s((const char*)(data_ + pos_), (size_t)utf8Len);
        pos_ += (size_t)utf8Len;
        return s;
    }

    std::vector<uint8_t> ReadBytes() {
        int32_t n = ReadI32();
        if (n <= 0) return std::vector<uint8_t>();
        if (Remaining() < (size_t)n) { pos_ = size_; return std::vector<uint8_t>(); }
        std::vector<uint8_t> b(data_ + pos_, data_ + pos_ + n);
        pos_ += (size_t)n;
        return b;
    }

    int32_t ReadCount() { return ReadI32(); }

private:
    uint8_t ReadByte() {
        if (pos_ >= size_) return 0;
        return data_[pos_++];
    }
    const uint8_t* data_;
    size_t size_;
    size_t pos_;
};

} // namespace mp
""";

    private const string NetClientH = """
// <auto-generated> 由 ClientGen 生成，请勿手动修改。
#pragma once
// 客户端 TCP 网络层：帧格式与服务器一致 [TotalLength(4)][MsgId(4)][Payload]
//   - TotalLength = 4 + Payload.Length（小端 int32）
// 跨平台：Windows（Winsock）/ Linux（POSIX）。UE 中可放进独立线程或直接调用 Poll()。
#include <cstdint>
#include <functional>
#include <string>
#include <vector>

class NetClient {
public:
    NetClient() = default;
    ~NetClient() { Close(); }

    /// <summary>连接 Gateway（阻塞）。成功返回 true。</summary>
    bool Connect(const std::string& host, uint16_t port);
    /// <summary>断开连接。</summary>
    void Close();
    bool IsConnected() const { return sock_ != -1; }

    /// <summary>发送一条完整负载（自动加 [TotalLength][MsgId] 帧头）。</summary>
    void Send(int32_t msgId, const uint8_t* payload, int32_t len);
    void Send(int32_t msgId, const std::vector<uint8_t>& payload) { Send(msgId, payload.data(), (int32_t)payload.size()); }

    /// <summary>非阻塞接收泵：解析完整帧后回调 onMessage(msgId, payload, payloadLen)。周期调用。</summary>
    void Poll(std::function<void(int32_t, const uint8_t*, int32_t)> onMessage);

private:
    int sock_ = -1;
    std::vector<uint8_t> recv_;
    void Append(const uint8_t* data, int32_t len);
    bool ParseFrames(std::function<void(int32_t, const uint8_t*, int32_t)> onMessage);
};
""";

    private const string NetClientCpp = """
// <auto-generated> 由 ClientGen 生成，请勿手动修改。
#include "NetClient.h"

#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
#pragma comment(lib, "ws2_32.lib")
#else
#include <arpa/inet.h>
#include <netdb.h>
#include <netinet/in.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <unistd.h>
#define INVALID_SOCKET (-1)
#define SOCKET_ERROR (-1)
#define closesocket close
#endif

#include <cstring>

static inline int32_t ReadI32LE(const uint8_t* p) {
    return (int32_t)((uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24));
}

bool NetClient::Connect(const std::string& host, uint16_t port) {
    Close();
#ifdef _WIN32
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) return false;
#endif
    sock_ = (int)socket(AF_INET, SOCK_STREAM, 0);
    if (sock_ == (int)INVALID_SOCKET) return false;

    struct sockaddr_in addr;
    std::memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    if (inet_pton(AF_INET, host.c_str(), &addr.sin_addr) != 1) {
        struct hostent* he = gethostbyname(host.c_str());
        if (!he) { Close(); return false; }
        std::memcpy(&addr.sin_addr, he->h_addr, (size_t)he->h_length);
    }
    if (connect(sock_, (struct sockaddr*)&addr, sizeof(addr)) == SOCKET_ERROR) {
        Close();
        return false;
    }
    recv_.clear();
    return true;
}

void NetClient::Close() {
    if (sock_ != (int)INVALID_SOCKET && sock_ != -1) {
#ifdef _WIN32
        shutdown(sock_, SD_BOTH);
        closesocket(sock_);
#else
        shutdown(sock_, SHUT_RDWR);
        closesocket(sock_);
#endif
    }
    sock_ = -1;
    recv_.clear();
}

void NetClient::Send(int32_t msgId, const uint8_t* payload, int32_t len) {
    if (sock_ == -1) return;
    int32_t inner = 4 + len;
    std::vector<uint8_t> frame(4 + inner);
    frame[0] = (uint8_t)(inner & 0xFF); frame[1] = (uint8_t)((inner >> 8) & 0xFF);
    frame[2] = (uint8_t)((inner >> 16) & 0xFF); frame[3] = (uint8_t)((inner >> 24) & 0xFF);
    frame[4] = (uint8_t)(msgId & 0xFF); frame[5] = (uint8_t)((msgId >> 8) & 0xFF);
    frame[6] = (uint8_t)((msgId >> 16) & 0xFF); frame[7] = (uint8_t)((msgId >> 24) & 0xFF);
    if (len > 0) std::memcpy(&frame[8], payload, (size_t)len);
#ifdef _WIN32
    send(sock_, (const char*)frame.data(), (int)frame.size(), 0);
#else
    send(sock_, frame.data(), frame.size(), 0);
#endif
}

void NetClient::Poll(std::function<void(int32_t, const uint8_t*, int32_t)> onMessage) {
    if (sock_ == -1) return;
    uint8_t tmp[4096];
#ifdef _WIN32
    u_long avail = 0;
    while (ioctlsocket(sock_, FIONREAD, &avail) == 0 && avail > 0) {
        int n = recv(sock_, (char*)tmp, sizeof(tmp), 0);
        if (n <= 0) { Close(); return; }
        Append(tmp, n);
    }
#else
    for (;;) {
        fd_set rset;
        FD_ZERO(&rset);
        FD_SET(sock_, &rset);
        struct timeval tv = { 0, 0 };
        if (select(sock_ + 1, &rset, nullptr, nullptr, &tv) <= 0) break;
        int n = (int)recv(sock_, tmp, sizeof(tmp), 0);
        if (n <= 0) { Close(); return; }
        Append(tmp, n);
    }
#endif
    if (!ParseFrames(onMessage)) Close();
}

void NetClient::Append(const uint8_t* data, int32_t len) {
    recv_.insert(recv_.end(), data, data + len);
}

bool NetClient::ParseFrames(std::function<void(int32_t, const uint8_t*, int32_t)> onMessage) {
    size_t pos = 0;
    for (;;) {
        if (recv_.size() - pos < 4) break;
        int32_t total = ReadI32LE(&recv_[pos]);
        if (total < 4 || recv_.size() - pos - 4 < (size_t)total) break; // 不完整帧
        int32_t msgId = ReadI32LE(&recv_[pos + 4]);
        onMessage(msgId, &recv_[pos + 8], total - 4);
        pos += 4 + (size_t)total;
    }
    if (pos > 0) {
        recv_.erase(recv_.begin(), recv_.begin() + (long)pos);
    }
    return true;
}
""";

    private const string DemoCpp = """
// 客户端示例：连接 Gateway -> 登录 -> 收到 LoginResult
// 编译（示例）：g++ -std=c++17 Demo.cpp NetClient.cpp -o demo -pthread  （Windows 加 -lws2_32）
// UE：把 MemoryPack.h / Messages.h / NetClient.* 放进模块，在 Tick/线程中调用。
#include <chrono>
#include <cstdio>
#include <thread>
#include "NetClient.h"
#include "Messages.h"

static void SleepMillis(int ms) {
    std::this_thread::sleep_for(std::chrono::milliseconds(ms));
}

int main() {
    NetClient client;
    if (!client.Connect("127.0.0.1", 31300)) {
        std::printf("连接失败\n");
        return 1;
    }

    // 登录（MemoryPack 兼容负载）
    ClientProtocol::Login login;
    login.Account = "demo";
    login.Password = "demo123";
    std::vector<uint8_t> payload = login.Serialize();
    client.Send(ClientProtocol::LoginMsgId, payload);

    // 主循环周期性接收（最多 3 秒）
    for (int i = 0; i < 300; ++i) {
        client.Poll([](int32_t msgId, const uint8_t* data, int32_t len) {
            if (msgId == ClientProtocol::LoginResultMsgId) {
                auto r = ClientProtocol::LoginResult::Deserialize(data, (size_t)len);
                std::printf("登录成功=%d 昵称=%s UserId=%d\n", r.Success ? 1 : 0, r.Nickname.c_str(), r.UserId);
            } else {
                std::printf("收到 MsgId=%d 长度=%d\n", msgId, len);
            }
        });
        SleepMillis(10);
    }
    client.Close();
    return 0;
}
""";

    private const string Readme = """
# UE 客户端（Net-Game-Server 协议）

零引擎依赖的 C++ 客户端，直接导入 Unreal Engine（或任意 C++ 工程）即可与服务器通信。

## 文件
- `MemoryPack.h`  —— 与服务器 MemoryPack 二进制格式逐字节兼容的编解码器（header-only）
- `Messages.h`    —— 消息结构体 + Serialize/Deserialize + <Name>MsgId 常量（header-only）
- `NetClient.h/.cpp` —— 标准 TCP 客户端（Winsock / POSIX）
- `Demo.cpp`      —— 连接 + 登录示例

## UE 集成步骤
1. 把 `MemoryPack.h`、`Messages.h`、`NetClient.h`、`NetClient.cpp` 拷入你的模块/插件
   （如 `Source/YourGame/Private/Net/`），`Messages.h` 仅依赖 `MemoryPack.h`。
2. 在任意 Actor/组件里持有 `NetClient`，在 `Tick` 中调用 `Poll(OnMessage)`：
   ```cpp
   NetClient Net;
   Net.Connect("127.0.0.1", 31300);          // 建议放后台线程或 BeginPlay
   ClientProtocol::Login L; L.Account = "demo"; L.Password = "demo123";
   Net.Send(ClientProtocol::LoginMsgId, L.Serialize());
   // Tick 里：
   Net.Poll([this](int32_t MsgId, const uint8_t* Data, int32_t Len) {
       if (MsgId == ClientProtocol::LoginResultMsgId) {
           auto R = ClientProtocol::LoginResult::Deserialize(Data, (size_t)Len);
           // R.Success / R.Nickname / R.UserId ...
       }
   });
   ```
3. 也可改用 UE 原生 `FSocket`：帧格式极简（`[TotalLength(4)][MsgId(4)][Payload]`），
   `MemoryPack.h` 的编解码与引擎无关，直接复用。

## 帧格式（与服务器 Gateway 一致）
```
[TotalLength(int32 LE) = 4 + Payload.Length][MsgId(int32 LE)][Payload]
```
Payload = 消息体（MemoryPack 兼容二进制）。也可直接发送 JSON 文本负载
（以 `{` 开头），服务器 `jsonFallback` 自动识别（字段名 PascalCase）。

## 字段类型
bool / int32 / int64 / float / string / bytes / list:T / map<string,string> / 结构体。
与服务器 `Framework.Protocol.Generated`（MemoryPack）逐字节兼容，由 ClientGen 从 `.def` 生成。
""";
}
