using System.Text;
using Protogen;

namespace ClientGen;

/// <summary>
/// Unity / .NET 客户端 C# 生成器。
/// 产物不依赖任何第三方库（无 MemoryPack / Newtonsoft），自带一个与服务器
/// MemoryPack 二进制格式逐字节兼容的编解码器，可直接导入 Unity 或任意 C# 工程。
/// </summary>
public static class UnityGenerator
{
    private const string Ns = "ClientProtocol";

    public static string GenerateMessageIds(List<ProtocolModel> protocols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 由 ClientGen 生成，请勿手动修改。");
        sb.AppendLine($"namespace {Ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>全协议消息 ID 常量（与服务器 Framework.Protocol.Generated.MessageIds 一致）。</summary>");
        sb.AppendLine("public static class MessageIds");
        sb.AppendLine("{");
        foreach (var proto in protocols)
        {
            foreach (var msg in proto.Messages)
            {
                sb.AppendLine($"    /// <summary>{msg.Id} {msg.Name} -> {msg.Target}</summary>");
                sb.AppendLine($"    public const int {Sanitize(msg.Name)} = {msg.Id};");
            }
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateCodec() => CodecTemplate;

    public static string GenerateMessages(List<ProtocolModel> protocols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 由 ClientGen 生成，请勿手动修改。");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Ns};");
        sb.AppendLine();

        // 结构体
        foreach (var proto in protocols)
        {
            foreach (var s in proto.Structs)
            {
                AppendStruct(sb, s, protocols);
            }
        }

        // 消息
        foreach (var proto in protocols)
        {
            foreach (var msg in proto.Messages)
            {
                AppendMessage(sb, msg, protocols);
            }
        }
        return sb.ToString();
    }

    public static string GenerateNetClient() => NetClientTemplate;

    public static string GenerateDemo() => DemoTemplate;

    // ---------- helpers ----------

    private static void AppendStruct(StringBuilder sb, StructModel s, List<ProtocolModel> protocols)
    {
        sb.AppendLine($"/// <summary>结构体 {s.Name}（{s.Fields.Count} 个成员）。</summary>");
        sb.AppendLine($"public sealed class {s.Name}");
        sb.AppendLine("{");
        foreach (var f in s.Fields)
        {
            sb.AppendLine($"    public {CsType(f.Type, protocols)} {f.Name} = {DefaultExpr(f.Type, protocols)};");
        }
        sb.AppendLine();
        sb.AppendLine("    /// <summary>写入成员数据（不含对象头字节；直接结构体字段会写入自身对象头）。</summary>");
        sb.AppendLine("    public void WriteBody(MpWriter w)");
        sb.AppendLine("    {");
        foreach (var f in s.Fields)
        {
            sb.AppendLine($"        {WriteExpr(f.Name, f.Type, protocols)}");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>读取成员数据（不含对象头字节）。</summary>");
        sb.AppendLine("    public void ReadBody(MpReader r)");
        sb.AppendLine("    {");
        foreach (var f in s.Fields)
        {
            sb.AppendLine($"        {ReadExpr(f.Name, f.Type, protocols)}");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendMessage(StringBuilder sb, MessageModel msg, List<ProtocolModel> protocols)
    {
        sb.AppendLine($"/// <summary>{msg.Id} {msg.Name} -> {msg.Target}（服务器目标 {msg.Target}）。</summary>");
        sb.AppendLine($"public sealed class {msg.Name} : IMessage");
        sb.AppendLine("{");
        sb.AppendLine($"    public const int MsgId = {msg.Id};");
        sb.AppendLine($"    public const string Target = \"{msg.Target}\";");
        sb.AppendLine($"    int IMessage.MessageId => MsgId;");
        foreach (var f in msg.Fields)
        {
            sb.AppendLine($"    public {CsType(f.Type, protocols)} {f.Name} = {DefaultExpr(f.Type, protocols)};");
        }
        sb.AppendLine();
        sb.AppendLine("    /// <summary>序列化为完整负载（对象头字节 + 成员数据），不含帧头。</summary>");
        sb.AppendLine("    public byte[] Serialize()");
        sb.AppendLine("    {");
        sb.AppendLine($"        var w = new MpWriter(); w.WriteHeader({msg.Fields.Count}); WriteBody(w); return w.ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>写入成员数据（不含对象头字节）。</summary>");
        sb.AppendLine("    public void WriteBody(MpWriter w)");
        sb.AppendLine("    {");
        foreach (var f in msg.Fields)
        {
            sb.AppendLine($"        {WriteExpr(f.Name, f.Type, protocols)}");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>读取成员数据（不含对象头字节）。</summary>");
        sb.AppendLine("    public void ReadBody(MpReader r)");
        sb.AppendLine("    {");
        foreach (var f in msg.Fields)
        {
            sb.AppendLine($"        {ReadExpr(f.Name, f.Type, protocols)}");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>从负载反序列化（跳过对象头字节后读成员数据）。</summary>");
        sb.AppendLine("    public static " + msg.Name + " Deserialize(byte[] data)");
        sb.AppendLine("    {");
        sb.AppendLine("        var r = new MpReader(data); r.SkipHeader();");
        sb.AppendLine($"        var m = new {msg.Name}(); m.ReadBody(r); return m;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---------- type mapping ----------

    public static string CsType(string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => "bool",
            FieldKind.Int32 => "int",
            FieldKind.Int64 => "long",
            FieldKind.Float => "float",
            FieldKind.String => "string",
            FieldKind.Bytes => "byte[]",
            FieldKind.List => $"List<{CsType(TypeHelpers.InnerOf(type), protocols)}>",
            FieldKind.Map => MapType(type, protocols),
            FieldKind.Struct => type,
            _ => type,
        };
    }

    private static string MapType(string type, List<ProtocolModel> protocols)
    {
        var (k, v) = TypeHelpers.MapPartsOf(type);
        return $"Dictionary<{CsType(k, protocols)}, {CsType(v, protocols)}>";
    }

    private static int MemberCount(string structName, List<ProtocolModel> protocols)
    {
        var st = ClientModel.FindStruct(protocols, structName);
        return st?.Fields.Count ?? 0;
    }

    private static string DefaultExpr(string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => "false",
            FieldKind.Int32 => "0",
            FieldKind.Int64 => "0L",
            FieldKind.Float => "0f",
            FieldKind.String => "\"\"",
            FieldKind.Bytes => "Array.Empty<byte>()",
            FieldKind.List => $"new List<{CsType(TypeHelpers.InnerOf(type), protocols)}>()",
            FieldKind.Map => $"new {MapType(type, protocols)}()",
            FieldKind.Struct => $"new {type}()",
            _ => "\"\"",
        };
    }

    private static string WriteExpr(string field, string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => $"w.WriteBool({field});",
            FieldKind.Int32 => $"w.WriteI32({field});",
            FieldKind.Int64 => $"w.WriteI64({field});",
            FieldKind.Float => $"w.WriteFloat({field});",
            FieldKind.String => $"w.WriteString({field});",
            FieldKind.Bytes => $"w.WriteBytes({field});",
            FieldKind.List => WriteListExpr(field, TypeHelpers.InnerOf(type), protocols),
            FieldKind.Map => WriteMapExpr(field, type, protocols),
            FieldKind.Struct => $"w.WriteHeader({MemberCount(type, protocols)}); {field}.WriteBody(w);",
            _ => "",
        };
    }

    private static string WriteListExpr(string field, string inner, List<ProtocolModel> protocols)
    {
        string elem = TypeHelpers.KindOf(inner, protocols) switch
        {
            FieldKind.Bool => "w.WriteBool(it);",
            FieldKind.Int32 => "w.WriteI32(it);",
            FieldKind.Int64 => "w.WriteI64(it);",
            FieldKind.Float => "w.WriteFloat(it);",
            FieldKind.String => "w.WriteString(it);",
            FieldKind.Bytes => "w.WriteBytes(it);",
            FieldKind.Struct => $"w.WriteHeader({MemberCount(inner, protocols)}); it.WriteBody(w);",
            FieldKind.List => throw new InvalidOperationException("嵌套 list 暂不支持: " + inner),
            FieldKind.Map => throw new InvalidOperationException("list:map 暂不支持: " + inner),
            _ => "",
        };
        return $"w.WriteCount({field}.Count); foreach (var it in {field}) {{ {elem} }}";
    }

    private static string WriteMapExpr(string field, string type, List<ProtocolModel> protocols)
    {
        var (k, v) = TypeHelpers.MapPartsOf(type);
        string key = WriteMapItem("kv.Key", k, protocols);
        string val = WriteMapItem("kv.Value", v, protocols);
        return $"w.WriteCount({field}.Count); foreach (var kv in {field}) {{ {key} {val} }}";
    }

    private static string WriteMapItem(string expr, string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => $"w.WriteBool({expr});",
            FieldKind.Int32 => $"w.WriteI32({expr});",
            FieldKind.Int64 => $"w.WriteI64({expr});",
            FieldKind.Float => $"w.WriteFloat({expr});",
            FieldKind.String => $"w.WriteString({expr});",
            FieldKind.Bytes => $"w.WriteBytes({expr});",
            FieldKind.Struct => $"w.WriteHeader({MemberCount(type, protocols)}); {expr}.WriteBody(w);",
            _ => "",
        };
    }

    private static string ReadExpr(string field, string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => $"{field} = r.ReadBool();",
            FieldKind.Int32 => $"{field} = r.ReadI32();",
            FieldKind.Int64 => $"{field} = r.ReadI64();",
            FieldKind.Float => $"{field} = r.ReadFloat();",
            FieldKind.String => $"{field} = r.ReadString();",
            FieldKind.Bytes => $"{field} = r.ReadBytes();",
            FieldKind.List => ReadListExpr(field, TypeHelpers.InnerOf(type), protocols),
            FieldKind.Map => ReadMapExpr(field, type, protocols),
            FieldKind.Struct => $"r.SkipHeader(); {field}.ReadBody(r);",
            _ => "",
        };
    }

    private static string ReadListExpr(string field, string inner, List<ProtocolModel> protocols)
    {
        string elem = TypeHelpers.KindOf(inner, protocols) switch
        {
            FieldKind.Bool => "var _e = r.ReadBool();",
            FieldKind.Int32 => "var _e = r.ReadI32();",
            FieldKind.Int64 => "var _e = r.ReadI64();",
            FieldKind.Float => "var _e = r.ReadFloat();",
            FieldKind.String => "var _e = r.ReadString();",
            FieldKind.Bytes => "var _e = r.ReadBytes();",
            FieldKind.Struct => $"var _e = new {inner}(); r.SkipHeader(); _e.ReadBody(r);",
            _ => "",
        };
        return $"int _n = r.ReadCount(); {field} = new List<{CsType(inner, protocols)}>(); for (int _i = 0; _i < _n; _i++) {{ {elem} {field}.Add(_e); }}";
    }

    private static string ReadMapExpr(string field, string type, List<ProtocolModel> protocols)
    {
        var (k, v) = TypeHelpers.MapPartsOf(type);
        string key = $"var _k = {ReadValueExpr(k, protocols)};";
        string val = $"var _v = {ReadValueExpr(v, protocols)};";
        return $"int _n = r.ReadCount(); {field} = new {MapType(type, protocols)}(); for (int _i = 0; _i < _n; _i++) {{ {key} {val} {field}[_k] = _v; }}";
    }

    private static string ReadValueExpr(string type, List<ProtocolModel> protocols)
    {
        return TypeHelpers.KindOf(type, protocols) switch
        {
            FieldKind.Bool => "r.ReadBool()",
            FieldKind.Int32 => "r.ReadI32()",
            FieldKind.Int64 => "r.ReadI64()",
            FieldKind.Float => "r.ReadFloat()",
            FieldKind.String => "r.ReadString()",
            FieldKind.Bytes => "r.ReadBytes()",
            FieldKind.Struct => $"(() => {{ var _s = new {type}(); r.SkipHeader(); _s.ReadBody(r); return _s; }})()",
            _ => "r.ReadI32()",
        };
    }

    private static string Sanitize(string name)
    {
        var sb = new StringBuilder(name.Length + 2);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch)) sb.Append(ch);
            else sb.Append('_');
        }
        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }

    // ---------- fixed templates ----------

    private const string CodecTemplate = """
// <auto-generated> 由 ClientGen 生成，请勿手动修改。
// 与服务器 MemoryPack 二进制格式逐字节兼容的零依赖编解码器。
// 格式要点（经真实 MemoryPack 输出实证）：
//   - 每个类对象（根对象 / 直接结构体字段 / 集合元素 / map 值）：1 字节对象头 = 成员数
//   - 数值：定长小端（bool=1 字节 / int32=4 / int64=8 / float=4 / double=8）
//   - 字符串：int32(~utf8len) + int32(utf16len) + UTF-8 字节；空串 = int32(0)
//   - byte[]：int32(len) + 字节
//   - List/Map：int32(count) + 元素（结构体元素带对象头）
#nullable enable
using System;
using System.Collections.Generic;
using System.Text;

namespace ClientProtocol
{
    /// <summary>帧载荷（不含帧头）的抽象。</summary>
    public interface IMessage
    {
        int MessageId { get; }
        byte[] Serialize();
    }

    /// <summary>MemoryPack 兼容二进制写入器。</summary>
    public sealed class MpWriter
    {
        private readonly List<byte> buf = new List<byte>();

        public void WriteByte(byte v) => buf.Add(v);
        public void WriteHeader(int memberCount) => buf.Add((byte)memberCount);
        public void WriteBool(bool v) => buf.Add(v ? (byte)1 : (byte)0);
        public void WriteI32(int v)
        {
            buf.Add((byte)v); buf.Add((byte)(v >> 8)); buf.Add((byte)(v >> 16)); buf.Add((byte)(v >> 24));
        }
        public void WriteI64(long v)
        {
            buf.Add((byte)v); buf.Add((byte)(v >> 8)); buf.Add((byte)(v >> 16)); buf.Add((byte)(v >> 24));
            buf.Add((byte)(v >> 32)); buf.Add((byte)(v >> 40)); buf.Add((byte)(v >> 48)); buf.Add((byte)(v >> 56));
        }
        public void WriteFloat(float v) => WriteI32(BitConverter.SingleToInt32Bits(v));
        public void WriteDouble(double v) => WriteI64(BitConverter.DoubleToInt64Bits(v));

        public void WriteString(string? s)
        {
            if (string.IsNullOrEmpty(s)) { WriteI32(0); return; }
            byte[] utf8 = Encoding.UTF8.GetBytes(s);
            WriteI32(~utf8.Length);
            WriteI32(s.Length); // UTF-16 长度
            buf.AddRange(utf8);
        }

        public void WriteBytes(byte[]? b)
        {
            if (b == null) { WriteI32(0); return; }
            WriteI32(b.Length);
            buf.AddRange(b);
        }

        public void WriteCount(int n) => WriteI32(n);

        public byte[] ToArray() => buf.ToArray();
    }

    /// <summary>MemoryPack 兼容二进制读取器。</summary>
    public sealed class MpReader
    {
        private readonly byte[] data;
        private int pos;

        public MpReader(byte[] data) { this.data = data; pos = 0; }

        /// <summary>跳过对象头字节（假定非空对象）。</summary>
        public void SkipHeader() { pos++; }

        public bool ReadBool() => data[pos++] != 0;

        public int ReadI32()
        {
            int v = data[pos] | (data[pos + 1] << 8) | (data[pos + 2] << 16) | (data[pos + 3] << 24);
            pos += 4;
            return v;
        }

        public long ReadI64()
        {
            long lo = (uint)ReadI32();
            long hi = (uint)ReadI32();
            return lo | (hi << 32);
        }

        public float ReadFloat() => BitConverter.Int32BitsToSingle(ReadI32());
        public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadI64());

        public string ReadString()
        {
            int v = ReadI32();
            if (v == 0) return "";
            int utf8Len = ~v;
            ReadI32(); // UTF-16 长度（客户端只需 UTF-8 字节）
            string s = Encoding.UTF8.GetString(data, pos, utf8Len);
            pos += utf8Len;
            return s;
        }

        public byte[] ReadBytes()
        {
            int n = ReadI32();
            if (n == 0) return Array.Empty<byte>();
            var b = new byte[n];
            Array.Copy(data, pos, b, 0, n);
            pos += n;
            return b;
        }

        public int ReadCount() => ReadI32();
    }
}
""";

    private const string NetClientTemplate = """
// <auto-generated> 由 ClientGen 生成，请勿手动修改。
// 客户端 TCP 网络层：帧格式与服务器一致 [TotalLength(4)][MsgId(4)][Payload]
//   - TotalLength = 4 + Payload.Length（小端 int32）
// 用法：
//   Unity：在 MonoBehaviour.Update() 中每帧调用 client.Poll(OnMessage)
//   纯 .NET：循环调用 client.Poll(OnMessage)（或后台线程）
#nullable enable
using System;
using System.Net.Sockets;

namespace ClientProtocol
{
    /// <summary>
    /// 与 Net-Game-Server Gateway 通信的轻量 TCP 客户端（零依赖，可直接导入 Unity / 任意 C#）。
    /// 发送用 MemoryPack 兼容编解码（MpWriter/MpReader），或直接传 JSON 负载（服务器 jsonFallback 接受）。
    /// </summary>
    public sealed class NetClient : IDisposable
    {
        private TcpClient? tcp;
        private NetworkStream? stream;
        private byte[] recv = new byte[16384];
        private int recvLen;

        public bool Connected => tcp != null && tcp.Connected && stream != null;

        /// <summary>连接 Gateway（阻塞）。</summary>
        public void Connect(string host, int port)
        {
            tcp = new TcpClient();
            tcp.Connect(host, port);
            stream = tcp.GetStream();
        }

        /// <summary>断开连接。</summary>
        public void Disconnect()
        {
            try { stream?.Close(); } catch { }
            try { tcp?.Close(); } catch { }
            stream = null; tcp = null; recvLen = 0;
        }

        /// <summary>发送一条完整负载（自动加 [TotalLength][MsgId] 帧头）。</summary>
        public void Send(int msgId, byte[] payload)
        {
            if (stream == null) throw new InvalidOperationException("NetClient 未连接");
            int inner = 4 + payload.Length;
            var frame = new byte[4 + inner];
            WriteInt32LE(frame, 0, inner);
            WriteInt32LE(frame, 4, msgId);
            Buffer.BlockCopy(payload, 0, frame, 8, payload.Length);
            stream.Write(frame, 0, frame.Length);
        }

        /// <summary>发送一个消息对象（用 MemoryPack 兼容序列化）。</summary>
        public void Send(IMessage message) => Send(message.MessageId, message.Serialize());

        /// <summary>发送 JSON 文本负载（服务器 jsonFallback 自动识别，字段名 PascalCase）。</summary>
        public void SendJson(int msgId, string jsonPayload)
        {
            var bytes = System.Text.Encoding.UTF8.GetBytes(jsonPayload);
            Send(msgId, bytes);
        }

        /// <summary>
        /// 非阻塞接收泵：读取 socket 已到达数据，解析完整帧后回调 onMessage(msgId, payload)。
        /// 必须在连接存续期间周期性调用（Unity Update / 主循环）。
        /// </summary>
        public void Poll(Action<int, byte[]> onMessage)
        {
            if (stream == null) return;

            // 1) 排空 socket（不足则扩容）
            while (stream.DataAvailable)
            {
                if (recvLen == recv.Length)
                {
                    var bigger = new byte[recv.Length * 2];
                    Buffer.BlockCopy(recv, 0, bigger, 0, recvLen);
                    recv = bigger;
                }
                int n = stream.Read(recv, recvLen, recv.Length - recvLen);
                if (n <= 0) { Disconnect(); return; }
                recvLen += n;
            }

            // 2) 解析完整帧 [TotalLength(4)][MsgId(4)][Payload]
            int pos = 0;
            while (true)
            {
                if (recvLen - pos < 4) break;
                int total = ReadInt32LE(recv, pos);
                if (total < 4 || recvLen - pos - 4 < total) break; // 不完整帧
                int msgId = ReadInt32LE(recv, pos + 4);
                var payload = new byte[total - 4];
                Buffer.BlockCopy(recv, pos + 8, payload, 0, total - 4);
                onMessage(msgId, payload);
                pos += 4 + total;
            }

            // 3) 压缩剩余字节
            if (pos > 0 && pos < recvLen)
            {
                Buffer.BlockCopy(recv, pos, recv, 0, recvLen - pos);
                recvLen -= pos;
            }
            else if (pos > 0)
            {
                recvLen = 0;
            }
        }

        public void Dispose() => Disconnect();

        private static void WriteInt32LE(byte[] dst, int offset, int v)
        {
            dst[offset] = (byte)v;
            dst[offset + 1] = (byte)(v >> 8);
            dst[offset + 2] = (byte)(v >> 16);
            dst[offset + 3] = (byte)(v >> 24);
        }

        private static int ReadInt32LE(byte[] src, int offset) =>
            src[offset] | (src[offset + 1] << 8) | (src[offset + 2] << 16) | (src[offset + 3] << 24);
    }
}
""";

    private const string DemoTemplate = """
// 客户端示例：连接 Gateway -> 登录 -> 收到 LoginResult
// Unity：把这段逻辑放进 MonoBehaviour，Update() 里调用 client.Poll(OnMessage) 即可。
#nullable enable
using System;
using ClientProtocol;

public static class Demo
{
    public static void Run()
    {
        var client = new NetClient();
        client.Connect("127.0.0.1", 31300);

        // 登录（MemoryPack 兼容负载）
        var login = new Login { Account = "demo", Password = "demo123" };
        client.Send(login);

        // 发送 JSON 负载（服务器 jsonFallback 自动解析，字段名 PascalCase）：
        // client.SendJson(MessageIds.Login, "{\"Account\":\"demo\",\"Password\":\"demo123\"}");

        // 主循环中周期性接收
        var deadline = DateTime.UtcNow.AddSeconds(3);
        while (DateTime.UtcNow < deadline)
        {
            client.Poll(OnMessage);
            System.Threading.Thread.Sleep(10);
        }

        client.Disconnect();

        void OnMessage(int msgId, byte[] payload)
        {
            switch (msgId)
            {
                case MessageIds.LoginResult:
                    var r = LoginResult.Deserialize(payload);
                    Console.WriteLine($"登录成功={r.Success} 昵称={r.Nickname} UserId={r.UserId}");
                    break;
                default:
                    Console.WriteLine($"收到 MsgId={msgId} 长度={payload.Length}");
                    break;
            }
        }
    }
}
""";
}
