// <auto-generated> 由 ClientGen 生成，请勿手动修改。
// 与服务器 MemoryPack 二进制格式逐字节兼容的零依赖编解码器。
// 格式要点（经真实 MemoryPack 输出实证）：
//   - 每个类对象（根对象 / 直接结构体字段 / 集合元素 / map 值）：1 字节对象头 = 成员数
//   - 数值：定长小端（bool=1 字节 / int32=4 / int64=8 / float=4 / double=8）
//   - 字符串：int32(~utf8len) + int32(utf16len) + UTF-8 字节；空串 = int32(0)
//   - byte[]：int32(len) + 字节
//   - List/Map：int32(count) + 元素（结构体元素带对象头）
#nullable enable
using System;
using System.Collections.Generic;
using System.Text;

namespace ClientProtocol
{
    /// <summary>帧载荷（不含帧头）的抽象。</summary>
    public interface IMessage
    {
        int MessageId { get; }
        byte[] Serialize();
    }

    /// <summary>MemoryPack 兼容二进制写入器。</summary>
    public sealed class MpWriter
    {
        private readonly List<byte> buf = new List<byte>();

        public void WriteByte(byte v) => buf.Add(v);
        public void WriteHeader(int memberCount) => buf.Add((byte)memberCount);
        public void WriteBool(bool v) => buf.Add(v ? (byte)1 : (byte)0);
        public void WriteI32(int v)
        {
            buf.Add((byte)v); buf.Add((byte)(v >> 8)); buf.Add((byte)(v >> 16)); buf.Add((byte)(v >> 24));
        }
        public void WriteI64(long v)
        {
            buf.Add((byte)v); buf.Add((byte)(v >> 8)); buf.Add((byte)(v >> 16)); buf.Add((byte)(v >> 24));
            buf.Add((byte)(v >> 32)); buf.Add((byte)(v >> 40)); buf.Add((byte)(v >> 48)); buf.Add((byte)(v >> 56));
        }
        public void WriteFloat(float v) => WriteI32(BitConverter.SingleToInt32Bits(v));
        public void WriteDouble(double v) => WriteI64(BitConverter.DoubleToInt64Bits(v));

        public void WriteString(string? s)
        {
            if (string.IsNullOrEmpty(s)) { WriteI32(0); return; }
            byte[] utf8 = Encoding.UTF8.GetBytes(s);
            WriteI32(~utf8.Length);
            WriteI32(s.Length); // UTF-16 长度
            buf.AddRange(utf8);
        }

        public void WriteBytes(byte[]? b)
        {
            if (b == null) { WriteI32(0); return; }
            WriteI32(b.Length);
            buf.AddRange(b);
        }

        public void WriteCount(int n) => WriteI32(n);

        public byte[] ToArray() => buf.ToArray();
    }

    /// <summary>MemoryPack 兼容二进制读取器。</summary>
    public sealed class MpReader
    {
        private readonly byte[] data;
        private int pos;

        public MpReader(byte[] data) { this.data = data; pos = 0; }

        /// <summary>跳过对象头字节（假定非空对象）。</summary>
        public void SkipHeader() { pos++; }

        public bool ReadBool() => data[pos++] != 0;

        public int ReadI32()
        {
            int v = data[pos] | (data[pos + 1] << 8) | (data[pos + 2] << 16) | (data[pos + 3] << 24);
            pos += 4;
            return v;
        }

        public long ReadI64()
        {
            long lo = (uint)ReadI32();
            long hi = (uint)ReadI32();
            return lo | (hi << 32);
        }

        public float ReadFloat() => BitConverter.Int32BitsToSingle(ReadI32());
        public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadI64());

        public string ReadString()
        {
            int v = ReadI32();
            if (v == 0) return "";
            int utf8Len = ~v;
            ReadI32(); // UTF-16 长度（客户端只需 UTF-8 字节）
            string s = Encoding.UTF8.GetString(data, pos, utf8Len);
            pos += utf8Len;
            return s;
        }

        public byte[] ReadBytes()
        {
            int n = ReadI32();
            if (n == 0) return Array.Empty<byte>();
            var b = new byte[n];
            Array.Copy(data, pos, b, 0, n);
            pos += n;
            return b;
        }

        public int ReadCount() => ReadI32();
    }
}