// <auto-generated> 由 ClientGen 生成，请勿手动修改。
// 与服务器 MemoryPack 二进制格式逐字节兼容的零依赖编解码器。
// 格式要点（经真实 MemoryPack 输出实证）：
//   - 每个类对象（根对象 / 直接结构体字段 / 集合元素 / map 值）：1 字节对象头 = 成员数
//   - 数值：定长小端（bool=1 字节 / int32=4 / int64=8 / float=4 / double=8）
//   - 字符串：null = int32(-1) / 空串 = int32(0) / 非空 = int32(~utf8len) + int32(utf16len) + UTF-8 字节
//   - byte[]：null = int32(-1) / 非空 = int32(len) + 字节（len=0 与 null 在字节上不同）
//   - List/Map：int32(count) + 元素（结构体元素带对象头）；null 集合 = int32(-1)
#nullable enable
using System;
using System.Collections.Generic;
using System.Text;

namespace ClientProtocol
{
    /// <summary>帧载荷（不含帧头）的抽象。</summary>
    public interface IMessage
    {
        int MessageId { get; }
        byte[] Serialize();
    }

    /// <summary>MemoryPack 兼容二进制写入器。</summary>
    public sealed class MpWriter
    {
        private readonly List<byte> buf = new List<byte>();

        public void WriteByte(byte v) => buf.Add(v);
        public void WriteHeader(int memberCount) => buf.Add((byte)memberCount);
        public void WriteBool(bool v) => buf.Add(v ? (byte)1 : (byte)0);
        public void WriteI32(int v)
        {
            buf.Add((byte)v); buf.Add((byte)(v >> 8)); buf.Add((byte)(v >> 16)); buf.Add((byte)(v >> 24));
        }
        public void WriteI64(long v)
        {
            buf.Add((byte)v); buf.Add((byte)(v >> 8)); buf.Add((byte)(v >> 16)); buf.Add((byte)(v >> 24));
            buf.Add((byte)(v >> 32)); buf.Add((byte)(v >> 40)); buf.Add((byte)(v >> 48)); buf.Add((byte)(v >> 56));
        }
        public void WriteFloat(float v) => WriteI32(BitConverter.SingleToInt32Bits(v));
        public void WriteDouble(double v) => WriteI64(BitConverter.DoubleToInt64Bits(v));

        public void WriteString(string? s)
        {
            // 三种形态必须与服务端 MemoryPack 一致：
            //   null = -1（短标记，**后面不跟** utf16 长度）/ 空串 = 0 / 非空 = ~utf8len + utf16len + 字节
            if (s == null) { WriteI32(-1); return; }
            if (s.Length == 0) { WriteI32(0); return; }
            byte[] utf8 = Encoding.UTF8.GetBytes(s);
            WriteI32(~utf8.Length);
            WriteI32(s.Length); // UTF-16 码元数（非字节数）
            buf.AddRange(utf8);
        }

        public void WriteBytes(byte[]? b)
        {
            // null = -1（MemoryPack 空集合标记）；空数组 = 0
            if (b == null) { WriteI32(-1); return; }
            WriteI32(b.Length);
            buf.AddRange(b);
        }

        public void WriteCount(int n) => WriteI32(n);

        public byte[] ToArray() => buf.ToArray();
    }

    /// <summary>MemoryPack 兼容二进制读取器。</summary>
    public sealed class MpReader
    {
        private readonly byte[] data;
        private int pos;

        public MpReader(byte[] data) { this.data = data; pos = 0; }

        /// <summary>跳过对象头字节（假定非空对象）。</summary>
        public void SkipHeader() { pos++; }

        public bool ReadBool() => data[pos++] != 0;

        public int ReadI32()
        {
            int v = data[pos] | (data[pos + 1] << 8) | (data[pos + 2] << 16) | (data[pos + 3] << 24);
            pos += 4;
            return v;
        }

        public long ReadI64()
        {
            long lo = (uint)ReadI32();
            long hi = (uint)ReadI32();
            return lo | (hi << 32);
        }

        public float ReadFloat() => BitConverter.Int32BitsToSingle(ReadI32());
        public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadI64());

        public string ReadString()
        {
            int v = ReadI32();
            // 三种形态（见上文字节格式）：0 = 空串；-1 = null；非空 = ~utf8len（**负数**，≤ -2）。
            // 只有 0 与 -1 是“无 utf16 长度字段”的短形态，必须在此返回；
            // 否则读到 null/空串时会多读 4 字节，把下一字段开头当成 utf16 长度吞掉 → 整包后续字段全部错位。
            // 反向陷阱：把 v <= 0 全当归一（曾这么改过）会把所有非空串当成空串——它们本身就是负数。
            // 客户端字段声明为非空 string，故 null 归一化为空串。
            if (v == 0 || v == -1) return "";
            int utf8Len = ~v;
            ReadI32(); // UTF-16 码元数（客户端只需 UTF-8 字节）
            string s = Encoding.UTF8.GetString(data, pos, utf8Len);
            pos += utf8Len;
            return s;
        }

        public byte[] ReadBytes()
        {
            int n = ReadI32();
            // n == -1 表示服务端写的是 null：必须按空数组处理，
            // 否则 new byte[-1] 直接抛 OverflowException，打断整个接收回调。
            if (n <= 0) return Array.Empty<byte>();
            var b = new byte[n];
            Array.Copy(data, pos, b, 0, n);
            pos += n;
            return b;
        }

        /// <summary>读取集合长度；null 集合（-1）归一化为 0，避免负长度参与分配。</summary>
        public int ReadCount() { int n = ReadI32(); return n > 0 ? n : 0; }
    }
}