// <auto-generated> 由 ClientGen 生成，请勿手动修改。
namespace ClientProtocol;

/// <summary>全协议消息 ID 常量（与服务器 Framework.Protocol.Generated.MessageIds 一致）。</summary>
public static class MessageIds
{
    /// <summary>40001 BattleJoin -> Battle</summary>
    public const int BattleJoin = 40001;
    /// <summary>40002 BattleJoinResult -> Battle</summary>
    public const int BattleJoinResult = 40002;
    /// <summary>40003 BattleFrameSync -> Battle</summary>
    public const int BattleFrameSync = 40003;
    /// <summary>40004 BattleLeaveRoom -> Battle</summary>
    public const int BattleLeaveRoom = 40004;
    /// <summary>40005 BattleLeaveRoomResult -> Battle</summary>
    public const int BattleLeaveRoomResult = 40005;
    /// <summary>40006 ScriptAction -> Battle</summary>
    public const int ScriptAction = 40006;
    /// <summary>40010 ClientTimeSync -> Battle</summary>
    public const int ClientTimeSync = 40010;
    /// <summary>40011 ServerTimeSync -> Battle</summary>
    public const int ServerTimeSync = 40011;
    /// <summary>40101 EntitySync -> Battle</summary>
    public const int EntitySync = 40101;
    /// <summary>40102 EntityEnterViewNotify -> Battle</summary>
    public const int EntityEnterViewNotify = 40102;
    /// <summary>40103 EntityLeaveViewNotify -> Battle</summary>
    public const int EntityLeaveViewNotify = 40103;
    /// <summary>40104 EntityStateUpdateNotify -> Battle</summary>
    public const int EntityStateUpdateNotify = 40104;
    /// <summary>40105 EntityDeltaSync -> Battle</summary>
    public const int EntityDeltaSync = 40105;
    /// <summary>40106 EntitySnapshot -> Battle</summary>
    public const int EntitySnapshot = 40106;
    /// <summary>30001 CenterMatch -> Center</summary>
    public const int CenterMatch = 30001;
    /// <summary>30002 CenterMatchResult -> Center</summary>
    public const int CenterMatchResult = 30002;
    /// <summary>30003 CenterCreateRoom -> Center</summary>
    public const int CenterCreateRoom = 30003;
    /// <summary>30004 CenterCreateRoomResult -> Center</summary>
    public const int CenterCreateRoomResult = 30004;
    /// <summary>30005 CenterListRooms -> Center</summary>
    public const int CenterListRooms = 30005;
    /// <summary>30006 CenterListRoomsResult -> Center</summary>
    public const int CenterListRoomsResult = 30006;
    /// <summary>30007 CenterJoinRoom -> Center</summary>
    public const int CenterJoinRoom = 30007;
    /// <summary>30008 CenterJoinRoomResult -> Center</summary>
    public const int CenterJoinRoomResult = 30008;
    /// <summary>30009 CenterCloseRoom -> Center</summary>
    public const int CenterCloseRoom = 30009;
    /// <summary>30010 CenterCloseRoomResult -> Center</summary>
    public const int CenterCloseRoomResult = 30010;
    /// <summary>30011 RoomClosedNotify -> Center</summary>
    public const int RoomClosedNotify = 30011;
    /// <summary>30012 CenterUpdateRoomSettings -> Center</summary>
    public const int CenterUpdateRoomSettings = 30012;
    /// <summary>30013 CenterUpdateRoomSettingsResult -> Center</summary>
    public const int CenterUpdateRoomSettingsResult = 30013;
    /// <summary>30014 RoomSettingsChangedNotify -> Center</summary>
    public const int RoomSettingsChangedNotify = 30014;
    /// <summary>30015 CenterStartRoomGame -> Center</summary>
    public const int CenterStartRoomGame = 30015;
    /// <summary>30016 CenterStartRoomGameResult -> Center</summary>
    public const int CenterStartRoomGameResult = 30016;
    /// <summary>30017 RoomGameStartedNotify -> Center</summary>
    public const int RoomGameStartedNotify = 30017;
    /// <summary>30018 RoomMemberList -> Center</summary>
    public const int RoomMemberList = 30018;
    /// <summary>30019 RoomMemberListResult -> Center</summary>
    public const int RoomMemberListResult = 30019;
    /// <summary>30020 RoomMemberListChangedNotify -> Center</summary>
    public const int RoomMemberListChangedNotify = 30020;
    /// <summary>30021 RoomReady -> Center</summary>
    public const int RoomReady = 30021;
    /// <summary>30022 RoomReadyResult -> Center</summary>
    public const int RoomReadyResult = 30022;
    /// <summary>30023 RoomReadyChangedNotify -> Center</summary>
    public const int RoomReadyChangedNotify = 30023;
    /// <summary>30024 RoomTransferOwner -> Center</summary>
    public const int RoomTransferOwner = 30024;
    /// <summary>30025 RoomTransferOwnerResult -> Center</summary>
    public const int RoomTransferOwnerResult = 30025;
    /// <summary>30026 RoomOwnerChangedNotify -> Center</summary>
    public const int RoomOwnerChangedNotify = 30026;
    /// <summary>30027 RoomKickMember -> Center</summary>
    public const int RoomKickMember = 30027;
    /// <summary>30028 RoomKickMemberResult -> Center</summary>
    public const int RoomKickMemberResult = 30028;
    /// <summary>30029 RoomKickedNotify -> Center</summary>
    public const int RoomKickedNotify = 30029;
    /// <summary>30030 CenterRoomChat -> Center</summary>
    public const int CenterRoomChat = 30030;
    /// <summary>30031 CenterRoomChatResult -> Center</summary>
    public const int CenterRoomChatResult = 30031;
    /// <summary>30032 CenterRoomChatNotify -> Center</summary>
    public const int CenterRoomChatNotify = 30032;
    /// <summary>30033 CenterLeaveRoom -> Center</summary>
    public const int CenterLeaveRoom = 30033;
    /// <summary>30034 CenterLeaveRoomResult -> Center</summary>
    public const int CenterLeaveRoomResult = 30034;
    /// <summary>60001 ChatSend -> Game</summary>
    public const int ChatSend = 60001;
    /// <summary>60002 ChatSendResult -> Game</summary>
    public const int ChatSendResult = 60002;
    /// <summary>60003 ChatNotify -> Game</summary>
    public const int ChatNotify = 60003;
    /// <summary>50001 FriendAdd -> Game</summary>
    public const int FriendAdd = 50001;
    /// <summary>50002 FriendAddResult -> Game</summary>
    public const int FriendAddResult = 50002;
    /// <summary>50003 FriendRemove -> Game</summary>
    public const int FriendRemove = 50003;
    /// <summary>50004 FriendRemoveResult -> Game</summary>
    public const int FriendRemoveResult = 50004;
    /// <summary>50005 FriendSetRemark -> Game</summary>
    public const int FriendSetRemark = 50005;
    /// <summary>50006 FriendSetRemarkResult -> Game</summary>
    public const int FriendSetRemarkResult = 50006;
    /// <summary>50007 FriendGetList -> Game</summary>
    public const int FriendGetList = 50007;
    /// <summary>50008 FriendListResult -> Game</summary>
    public const int FriendListResult = 50008;
    /// <summary>50009 FriendInviteGame -> Game</summary>
    public const int FriendInviteGame = 50009;
    /// <summary>50010 FriendInviteGameResult -> Game</summary>
    public const int FriendInviteGameResult = 50010;
    /// <summary>50011 FriendInviteGameNotify -> Game</summary>
    public const int FriendInviteGameNotify = 50011;
    /// <summary>50012 BlacklistAdd -> Game</summary>
    public const int BlacklistAdd = 50012;
    /// <summary>50013 BlacklistAddResult -> Game</summary>
    public const int BlacklistAddResult = 50013;
    /// <summary>50014 BlacklistRemove -> Game</summary>
    public const int BlacklistRemove = 50014;
    /// <summary>50015 BlacklistRemoveResult -> Game</summary>
    public const int BlacklistRemoveResult = 50015;
    /// <summary>50016 BlacklistGetList -> Game</summary>
    public const int BlacklistGetList = 50016;
    /// <summary>50017 BlacklistListResult -> Game</summary>
    public const int BlacklistListResult = 50017;
    /// <summary>50018 FriendApply -> Game</summary>
    public const int FriendApply = 50018;
    /// <summary>50019 FriendApplyResult -> Game</summary>
    public const int FriendApplyResult = 50019;
    /// <summary>50020 FriendApplyNotify -> Game</summary>
    public const int FriendApplyNotify = 50020;
    /// <summary>50021 FriendApplyList -> Game</summary>
    public const int FriendApplyList = 50021;
    /// <summary>50022 FriendApplyListResult -> Game</summary>
    public const int FriendApplyListResult = 50022;
    /// <summary>50023 FriendApplyHandle -> Game</summary>
    public const int FriendApplyHandle = 50023;
    /// <summary>50024 FriendApplyHandleResult -> Game</summary>
    public const int FriendApplyHandleResult = 50024;
    /// <summary>50025 FriendOnlineStatusNotify -> Game</summary>
    public const int FriendOnlineStatusNotify = 50025;
    /// <summary>50026 FriendInviteGameAck -> Game</summary>
    public const int FriendInviteGameAck = 50026;
    /// <summary>50027 FriendInviteGameAckResult -> Game</summary>
    public const int FriendInviteGameAckResult = 50027;
    /// <summary>50028 FriendInviteGameAckNotify -> Game</summary>
    public const int FriendInviteGameAckNotify = 50028;
    /// <summary>10001 Login -> Login</summary>
    public const int Login = 10001;
    /// <summary>10002 LoginResult -> Login</summary>
    public const int LoginResult = 10002;
    /// <summary>10003 Register -> Login</summary>
    public const int Register = 10003;
    /// <summary>10004 RegisterResult -> Login</summary>
    public const int RegisterResult = 10004;
    /// <summary>10005 Logout -> Login</summary>
    public const int Logout = 10005;
    /// <summary>10006 LogoutResult -> Login</summary>
    public const int LogoutResult = 10006;
    /// <summary>10007 ResetPassword -> Login</summary>
    public const int ResetPassword = 10007;
    /// <summary>10008 ResetPasswordResult -> Login</summary>
    public const int ResetPasswordResult = 10008;
    /// <summary>10009 UpdateNickname -> Login</summary>
    public const int UpdateNickname = 10009;
    /// <summary>10010 UpdateNicknameResult -> Login</summary>
    public const int UpdateNicknameResult = 10010;
    /// <summary>10011 KickedOff -> Login</summary>
    public const int KickedOff = 10011;
    /// <summary>10012 FindPasswordWithCode -> Login</summary>
    public const int FindPasswordWithCode = 10012;
    /// <summary>10013 FindPasswordWithCodeResult -> Login</summary>
    public const int FindPasswordWithCodeResult = 10013;
}
