// <auto-generated> 由 ClientGen 生成，请勿手动修改。
// 客户端 TCP 网络层：帧格式与服务器一致 [TotalLength(4)][MsgId(4)][Payload]
//   - TotalLength = 4 + Payload.Length（小端 int32）
// 用法：
//   Unity：在 MonoBehaviour.Update() 中每帧调用 client.Poll(OnMessage)
//   纯 .NET：循环调用 client.Poll(OnMessage)（或后台线程）
#nullable enable
using System;
using System.Net.Sockets;

namespace ClientProtocol
{
    /// <summary>
    /// 与 Net-Game-Server Gateway 通信的轻量 TCP 客户端（零依赖，可直接导入 Unity / 任意 C#）。
    /// 发送用 MemoryPack 兼容编解码（MpWriter/MpReader），或直接传 JSON 负载（服务器 jsonFallback 接受）。
    /// </summary>
    public sealed class NetClient : IDisposable
    {
        private TcpClient? tcp;
        private NetworkStream? stream;
        private byte[] recv = new byte[16384];
        private int recvLen;

        public bool Connected => tcp != null && tcp.Connected && stream != null;

        /// <summary>连接 Gateway（阻塞）。</summary>
        public void Connect(string host, int port)
        {
            tcp = new TcpClient();
            tcp.Connect(host, port);
            stream = tcp.GetStream();
        }

        /// <summary>断开连接。</summary>
        public void Disconnect()
        {
            try { stream?.Close(); } catch { }
            try { tcp?.Close(); } catch { }
            stream = null; tcp = null; recvLen = 0;
        }

        /// <summary>发送一条完整负载（自动加 [TotalLength][MsgId] 帧头）。</summary>
        public void Send(int msgId, byte[] payload)
        {
            if (stream == null) throw new InvalidOperationException("NetClient 未连接");
            int inner = 4 + payload.Length;
            var frame = new byte[4 + inner];
            WriteInt32LE(frame, 0, inner);
            WriteInt32LE(frame, 4, msgId);
            Buffer.BlockCopy(payload, 0, frame, 8, payload.Length);
            stream.Write(frame, 0, frame.Length);
        }

        /// <summary>发送一个消息对象（用 MemoryPack 兼容序列化）。</summary>
        public void Send(IMessage message) => Send(message.MessageId, message.Serialize());

        /// <summary>发送 JSON 文本负载（服务器 jsonFallback 自动识别，字段名 PascalCase）。</summary>
        public void SendJson(int msgId, string jsonPayload)
        {
            var bytes = System.Text.Encoding.UTF8.GetBytes(jsonPayload);
            Send(msgId, bytes);
        }

        /// <summary>
        /// 非阻塞接收泵：读取 socket 已到达数据，解析完整帧后回调 onMessage(msgId, payload)。
        /// 必须在连接存续期间周期性调用（Unity Update / 主循环）。
        /// </summary>
        public void Poll(Action<int, byte[]> onMessage)
        {
            if (stream == null) return;

            // 1) 排空 socket（不足则扩容）
            while (stream.DataAvailable)
            {
                if (recvLen == recv.Length)
                {
                    var bigger = new byte[recv.Length * 2];
                    Buffer.BlockCopy(recv, 0, bigger, 0, recvLen);
                    recv = bigger;
                }
                int n = stream.Read(recv, recvLen, recv.Length - recvLen);
                if (n <= 0) { Disconnect(); return; }
                recvLen += n;
            }

            // 2) 解析完整帧 [TotalLength(4)][MsgId(4)][Payload]
            int pos = 0;
            while (true)
            {
                if (recvLen - pos < 4) break;
                int total = ReadInt32LE(recv, pos);
                if (total < 4 || recvLen - pos - 4 < total) break; // 不完整帧
                int msgId = ReadInt32LE(recv, pos + 4);
                var payload = new byte[total - 4];
                Buffer.BlockCopy(recv, pos + 8, payload, 0, total - 4);
                onMessage(msgId, payload);
                pos += 4 + total;
            }

            // 3) 压缩剩余字节
            if (pos > 0 && pos < recvLen)
            {
                Buffer.BlockCopy(recv, pos, recv, 0, recvLen - pos);
                recvLen -= pos;
            }
            else if (pos > 0)
            {
                recvLen = 0;
            }
        }

        public void Dispose() => Disconnect();

        private static void WriteInt32LE(byte[] dst, int offset, int v)
        {
            dst[offset] = (byte)v;
            dst[offset + 1] = (byte)(v >> 8);
            dst[offset + 2] = (byte)(v >> 16);
            dst[offset + 3] = (byte)(v >> 24);
        }

        private static int ReadInt32LE(byte[] src, int offset) =>
            src[offset] | (src[offset + 1] << 8) | (src[offset + 2] << 16) | (src[offset + 3] << 24);
    }
}