<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Supervisor</RootNamespace>
    <AssemblyName>Supervisor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="supervisor.sample.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
