<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Network\Network.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Framework\Framework.Entity\Framework.Entity.csproj" />
    <ProjectReference Include="..\Framework\Framework.Persistence\Framework.Persistence.csproj" />
    <ProjectReference Include="..\Framework\Framework.Tick\Framework.Tick.csproj" />
    <ProjectReference Include="..\Framework\Framework.Protocol\Framework.Protocol.csproj" />
    <ProjectReference Include="..\Framework\Framework.Scripting\Framework.Scripting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configs\Scenes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
