// <auto-generated> 由 ClientGen 生成，请勿手动修改。
#pragma once
// 与服务器 MemoryPack 二进制格式逐字节兼容的零依赖编解码器（纯 C++11，header-only）。
// 格式要点（经真实 MemoryPack 输出实证）：
//   - 每个类对象（根对象 / 直接结构体字段 / 集合元素 / map 值）：1 字节对象头 = 成员数
//   - 数值：定长小端（bool=1 / int32=4 / int64=8 / float=4 / double=8）
//   - 字符串：int32(~utf8len) + int32(utf16len) + UTF-8 字节；空串 = int32(0)
//   - byte[]：int32(len) + 字节
//   - List/Map：int32(count) + 元素（结构体元素带对象头）
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

namespace mp {

// 统计 UTF-8 字节串对应的 UTF-16 码元数（与 C# string.Length / .NET char 数一致）
inline int32_t Utf16Length(const std::string& utf8) {
    int32_t n = 0;
    size_t i = 0;
    const size_t len = utf8.size();
    while (i < len) {
        uint8_t c = (uint8_t)utf8[i];
        if (c < 0x80) { n += 1; i += 1; }
        else if ((c >> 5) == 0x06) { n += 1; i += 2; }       // 2 字节
        else if ((c >> 4) == 0x0E) { n += 1; i += 3; }       // 3 字节（BMP）
        else if ((c >> 3) == 0x1E) { n += 2; i += 4; }       // 4 字节（代理对 = 2 码元）
        else { i += 1; }
    }
    return n;
}

/// <summary>MemoryPack 兼容二进制写入器。</summary>
class Writer {
public:
    void WriteByte(uint8_t v) { buf_.push_back(v); }
    void WriteHeader(int memberCount) { buf_.push_back((uint8_t)memberCount); }
    void WriteBool(bool v) { buf_.push_back(v ? 1 : 0); }
    void WriteI32(int32_t v) {
        buf_.push_back((uint8_t)(v & 0xFF));
        buf_.push_back((uint8_t)((v >> 8) & 0xFF));
        buf_.push_back((uint8_t)((v >> 16) & 0xFF));
        buf_.push_back((uint8_t)((v >> 24) & 0xFF));
    }
    void WriteI64(int64_t v) {
        buf_.push_back((uint8_t)(v & 0xFF));
        buf_.push_back((uint8_t)((v >> 8) & 0xFF));
        buf_.push_back((uint8_t)((v >> 16) & 0xFF));
        buf_.push_back((uint8_t)((v >> 24) & 0xFF));
        buf_.push_back((uint8_t)((v >> 32) & 0xFF));
        buf_.push_back((uint8_t)((v >> 40) & 0xFF));
        buf_.push_back((uint8_t)((v >> 48) & 0xFF));
        buf_.push_back((uint8_t)((v >> 56) & 0xFF));
    }
    void WriteFloat(float f) { uint32_t u; std::memcpy(&u, &f, 4); WriteU32(u); }
    void WriteDouble(double d) { uint64_t u; std::memcpy(&u, &d, 8); WriteU64(u); }

    void WriteString(const std::string& s) {
        if (s.empty()) { WriteI32(0); return; }
        int32_t utf8Len = (int32_t)s.size();
        int32_t utf16Len = Utf16Length(s);
        WriteI32(~utf8Len);
        WriteI32(utf16Len);
        buf_.insert(buf_.end(), s.begin(), s.end());
    }

    void WriteBytes(const std::vector<uint8_t>& b) {
        WriteI32((int32_t)b.size());
        if (!b.empty()) buf_.insert(buf_.end(), b.begin(), b.end());
    }

    void WriteCount(int32_t n) { WriteI32(n); }

    std::vector<uint8_t> Take() { return std::move(buf_); }

private:
    void WriteU32(uint32_t v) {
        buf_.push_back((uint8_t)(v & 0xFF));
        buf_.push_back((uint8_t)((v >> 8) & 0xFF));
        buf_.push_back((uint8_t)((v >> 16) & 0xFF));
        buf_.push_back((uint8_t)((v >> 24) & 0xFF));
    }
    void WriteU64(uint64_t v) {
        buf_.push_back((uint8_t)(v & 0xFF));
        buf_.push_back((uint8_t)((v >> 8) & 0xFF));
        buf_.push_back((uint8_t)((v >> 16) & 0xFF));
        buf_.push_back((uint8_t)((v >> 24) & 0xFF));
        buf_.push_back((uint8_t)((v >> 32) & 0xFF));
        buf_.push_back((uint8_t)((v >> 40) & 0xFF));
        buf_.push_back((uint8_t)((v >> 48) & 0xFF));
        buf_.push_back((uint8_t)((v >> 56) & 0xFF));
    }
    std::vector<uint8_t> buf_;
};

/// <summary>MemoryPack 兼容二进制读取器（带越界保护）。</summary>
class Reader {
public:
    Reader(const uint8_t* data, size_t size) : data_(data), size_(size), pos_(0) {}

    void SkipHeader() { pos_ += 1; }
    bool Ok() const { return pos_ <= size_; }
    size_t Remaining() const { return size_ - pos_; }

    bool ReadBool() { return ReadByte() != 0; }

    int32_t ReadI32() {
        if (Remaining() < 4) return 0;
        uint32_t v = (uint32_t)data_[pos_] | ((uint32_t)data_[pos_ + 1] << 8)
                   | ((uint32_t)data_[pos_ + 2] << 16) | ((uint32_t)data_[pos_ + 3] << 24);
        pos_ += 4;
        return (int32_t)v;
    }

    int64_t ReadI64() {
        uint64_t lo = (uint32_t)ReadI32();
        uint64_t hi = (uint32_t)ReadI32();
        return (int64_t)(lo | (hi << 32));
    }

    float ReadFloat() {
        uint32_t u = (uint32_t)ReadI32();
        float f;
        std::memcpy(&f, &u, 4);
        return f;
    }

    double ReadDouble() {
        uint64_t lo = (uint32_t)ReadI32();
        uint64_t hi = (uint32_t)ReadI32();
        uint64_t u = lo | (hi << 32);
        double d;
        std::memcpy(&d, &u, 8);
        return d;
    }

    std::string ReadString() {
        int32_t v = ReadI32();
        if (v == 0) return std::string();
        int32_t utf8Len = ~v;
        ReadI32(); // UTF-16 长度（客户端只需 UTF-8 字节）
        if (Remaining() < (size_t)utf8Len) { pos_ = size_; return std::string(); }
        std::string s((const char*)(data_ + pos_), (size_t)utf8Len);
        pos_ += (size_t)utf8Len;
        return s;
    }

    std::vector<uint8_t> ReadBytes() {
        int32_t n = ReadI32();
        if (n <= 0) return std::vector<uint8_t>();
        if (Remaining() < (size_t)n) { pos_ = size_; return std::vector<uint8_t>(); }
        std::vector<uint8_t> b(data_ + pos_, data_ + pos_ + n);
        pos_ += (size_t)n;
        return b;
    }

    int32_t ReadCount() { return ReadI32(); }

private:
    uint8_t ReadByte() {
        if (pos_ >= size_) return 0;
        return data_[pos_++];
    }
    const uint8_t* data_;
    size_t size_;
    size_t pos_;
};

} // namespace mp