// <auto-generated> 由 ClientGen 生成，请勿手动修改。
#include "NetClient.h"

#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
#pragma comment(lib, "ws2_32.lib")
#else
#include <arpa/inet.h>
#include <netdb.h>
#include <netinet/in.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <unistd.h>
#define INVALID_SOCKET (-1)
#define SOCKET_ERROR (-1)
#define closesocket close
#endif

#include <cstring>

static inline int32_t ReadI32LE(const uint8_t* p) {
    return (int32_t)((uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24));
}

bool NetClient::Connect(const std::string& host, uint16_t port) {
    Close();
#ifdef _WIN32
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) return false;
#endif
    sock_ = (int)socket(AF_INET, SOCK_STREAM, 0);
    if (sock_ == (int)INVALID_SOCKET) return false;

    struct sockaddr_in addr;
    std::memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    if (inet_pton(AF_INET, host.c_str(), &addr.sin_addr) != 1) {
        struct hostent* he = gethostbyname(host.c_str());
        if (!he) { Close(); return false; }
        std::memcpy(&addr.sin_addr, he->h_addr, (size_t)he->h_length);
    }
    if (connect(sock_, (struct sockaddr*)&addr, sizeof(addr)) == SOCKET_ERROR) {
        Close();
        return false;
    }
    recv_.clear();
    return true;
}

void NetClient::Close() {
    if (sock_ != (int)INVALID_SOCKET && sock_ != -1) {
#ifdef _WIN32
        shutdown(sock_, SD_BOTH);
        closesocket(sock_);
#else
        shutdown(sock_, SHUT_RDWR);
        closesocket(sock_);
#endif
    }
    sock_ = -1;
    recv_.clear();
}

void NetClient::Send(int32_t msgId, const uint8_t* payload, int32_t len) {
    if (sock_ == -1) return;
    int32_t inner = 4 + len;
    std::vector<uint8_t> frame(4 + inner);
    frame[0] = (uint8_t)(inner & 0xFF); frame[1] = (uint8_t)((inner >> 8) & 0xFF);
    frame[2] = (uint8_t)((inner >> 16) & 0xFF); frame[3] = (uint8_t)((inner >> 24) & 0xFF);
    frame[4] = (uint8_t)(msgId & 0xFF); frame[5] = (uint8_t)((msgId >> 8) & 0xFF);
    frame[6] = (uint8_t)((msgId >> 16) & 0xFF); frame[7] = (uint8_t)((msgId >> 24) & 0xFF);
    if (len > 0) std::memcpy(&frame[8], payload, (size_t)len);
#ifdef _WIN32
    send(sock_, (const char*)frame.data(), (int)frame.size(), 0);
#else
    send(sock_, frame.data(), frame.size(), 0);
#endif
}

void NetClient::Poll(std::function<void(int32_t, const uint8_t*, int32_t)> onMessage) {
    if (sock_ == -1) return;
    uint8_t tmp[4096];
#ifdef _WIN32
    u_long avail = 0;
    while (ioctlsocket(sock_, FIONREAD, &avail) == 0 && avail > 0) {
        int n = recv(sock_, (char*)tmp, sizeof(tmp), 0);
        if (n <= 0) { Close(); return; }
        Append(tmp, n);
    }
#else
    for (;;) {
        fd_set rset;
        FD_ZERO(&rset);
        FD_SET(sock_, &rset);
        struct timeval tv = { 0, 0 };
        if (select(sock_ + 1, &rset, nullptr, nullptr, &tv) <= 0) break;
        int n = (int)recv(sock_, tmp, sizeof(tmp), 0);
        if (n <= 0) { Close(); return; }
        Append(tmp, n);
    }
#endif
    if (!ParseFrames(onMessage)) Close();
}

void NetClient::Append(const uint8_t* data, int32_t len) {
    recv_.insert(recv_.end(), data, data + len);
}

bool NetClient::ParseFrames(std::function<void(int32_t, const uint8_t*, int32_t)> onMessage) {
    size_t pos = 0;
    for (;;) {
        if (recv_.size() - pos < 4) break;
        int32_t total = ReadI32LE(&recv_[pos]);
        if (total < 4 || recv_.size() - pos - 4 < (size_t)total) break; // 不完整帧
        int32_t msgId = ReadI32LE(&recv_[pos + 4]);
        onMessage(msgId, &recv_[pos + 8], total - 4);
        pos += 4 + (size_t)total;
    }
    if (pos > 0) {
        recv_.erase(recv_.begin(), recv_.begin() + (long)pos);
    }
    return true;
}