// <auto-generated> 由 ClientGen 生成，请勿手动修改。
#pragma once
// 客户端 TCP 网络层：帧格式与服务器一致 [TotalLength(4)][MsgId(4)][Payload]
//   - TotalLength = 4 + Payload.Length（小端 int32）
// 跨平台：Windows（Winsock）/ Linux（POSIX）。UE 中可放进独立线程或直接调用 Poll()。
#include <cstdint>
#include <functional>
#include <string>
#include <vector>

class NetClient {
public:
    NetClient() = default;
    ~NetClient() { Close(); }

    /// <summary>连接 Gateway（阻塞）。成功返回 true。</summary>
    bool Connect(const std::string& host, uint16_t port);
    /// <summary>断开连接。</summary>
    void Close();
    bool IsConnected() const { return sock_ != -1; }

    /// <summary>发送一条完整负载（自动加 [TotalLength][MsgId] 帧头）。</summary>
    void Send(int32_t msgId, const uint8_t* payload, int32_t len);
    void Send(int32_t msgId, const std::vector<uint8_t>& payload) { Send(msgId, payload.data(), (int32_t)payload.size()); }

    /// <summary>非阻塞接收泵：解析完整帧后回调 onMessage(msgId, payload, payloadLen)。周期调用。</summary>
    void Poll(std::function<void(int32_t, const uint8_t*, int32_t)> onMessage);

private:
    int sock_ = -1;
    std::vector<uint8_t> recv_;
    void Append(const uint8_t* data, int32_t len);
    bool ParseFrames(std::function<void(int32_t, const uint8_t*, int32_t)> onMessage);
};